concert_app/config/routes.rb
Rails.application.routes.draw do
 

  resources :concerts
  get "/concerts/:id/details" => "concerts#details", as: "concert_details"
  get "/" => "concerts#home", as: "home"
  

end

concert_app/app/models/concert.rb
class Concert < ActiveRecord::Base
	
	def self.last_created_concerts
		# order(created_at: :desc).limit(n)
		where("date >= ?", Date.today.beginning_of_month)
	end

	def self.created_today
		# order(created_at: :desc).limit(n)
		where(date: Date.today)
	end
end

concert_app/app/models/site.rb
class Site < ActiveRecord::Base
	def self.created_today
		# order(created_at: :desc).limit(n)
		where(date: Date.today)
	end
end

concert_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

concert_app/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  def index
       @concerts = Concert.last_created_concerts
    if @concerts.empty? 
      render 'no_projects_found'
    end
   
  end

  def create
  end

  def new
    @concert = Concert.new

  end

  def show
  end

  def edit
  end

  def home
      @concerts = Concert.created_today
    if @concerts.empty? 
      render 'no_projects_found'
    end

    @monthly_concerts = Concert.last_created_concerts
    
  end

  def details 
    @concert = Concert.find params[:id]
  end 

 



end

concert_app/app/helpers/application_helper.rb
module ApplicationHelper
end

concert_app/app/helpers/concert_helper.rb
module ConcertHelper
end

concert_app/app/helpers/index_helper.rb
module IndexHelper
end

concert_app/app/views/concerts/create.html.erb
<h1>Concert#create</h1>
<p>Find me in app/views/concert/create.html.erb</p>

concert_app/app/views/concerts/details.html.erb
<h1><%=@concert.artist%></h1>

<h2><%= @concert.description%></h2>

<%= link_to("Today's Concerts", home_path)%> <br>
<%= link_to("Monthly Concerts", concerts_path)%>

concert_app/app/views/concerts/edit.html.erb
<h1>Concert#edit</h1>
<p>Find me in app/views/concert/edit.html.erb</p>

concert_app/app/views/concerts/home.html.erb
	<div class= "text-center">
		<h1 >welcome</h1>
		<ul class="col-lg-8 concert_list">
			<% @concerts.each do |concert| %>
				<li> <%= concert.artist%> -- <%= concert.venue%>, 
				<br><%= concert.city%> date: <%= concert.date%>
				<%= link_to('more_info', concert_details_path(concert))%>
				
				</li><br>		
			<%end%>
			
		</ul>
	</div>
	<div id="sidebar-wrapper" class ="my_sidebar col-lg-4 pre-scrollable">
 <!--            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <a href="#">
                        Concerts this Month
                    </a>
                </li>
                <li>
                    <a href="#">Dashboard</a>
                </li>
                <li>
                    <a href="#">Shortcuts</a>
                </li>
                <li>
                    <a href="#">Overview</a>
                </li>
                <li>
                    <a href="#">Events</a>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul> -->


     <ul>
      <li class="sidebar-brand">
                    <a href="#">
                        Concerts this Month
                    </a>
       </li>
	<% @monthly_concerts.each do |concert| %>
		<li> <%= concert.artist%> -- <%= concert.venue%>, 
		<br><%= concert.city%> date: <%= concert.date%>
		<%= link_to('more_info', concert_details_path(concert))%>
		
		</li><br>		
	<%end%>
	
	</ul>
     </div>

concert_app/app/views/concerts/index.html.erb
<h1>Concert#index</h1>



<ul>
	<% @concerts.each do |concert| %>
		<li> <%= concert.artist%> -- <%= concert.venue%>, 
		<br><%= concert.city%> date: <%= concert.date%>
		<%= link_to('more_info', concert_details_path(concert))%>
		
		</li><br>		
	<%end%>
	
</ul>

concert_app/app/views/concerts/new.html.erb
<h1>Concert#new</h1>


<%= form_for [@concert] do |f|%>
	<%= f.label :artist %>
	<%= f.text_field :artist %>
	<br>
	<%= f.label :date %>
	<%= f.date_field :date %>
	<br>
	<%= f.label :venue %>
	<%= f.text_field :venue %>
	<br>
	<%= f.label :venue %>
	<%= f.text_field :venue %>
	<br>
	<%= f.label :city %>
	<%= f.text_field :city %>
	<br>
	<%= f.label :price %>
	<%= f.number_field :price %>
	<br>
	<%= f.label :description %>
	<%= f.text_field :description %>
	<br>
	
	<%= f.submit 'Save' %>
	<%= link_to 'Cancel', concerts_path%>

<%end%>

concert_app/app/views/concerts/show.html.erb
<h1>Concert#show</h1>
<p>Find me in app/views/concert/show.html.erb</p>

concert_app/app/views/index/create.html.erb
<h1>Index#create</h1>
<p>Find me in app/views/index/create.html.erb</p>

concert_app/app/views/index/edit.html.erb
<h1>Index#edit</h1>
<p>Find me in app/views/index/edit.html.erb</p>

concert_app/app/views/index/new.html.erb
<h1>Index#new</h1>
<p>Find me in app/views/index/new.html.erb</p>

concert_app/app/views/index/show.html.erb
<h1>Index#show</h1>
<p>Find me in app/views/index/show.html.erb</p>

concert_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConcertApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<main class= "container">
	
<section class= "row"><header class = " header jumbotron">Marc's concerts app</header>
<%= yield %></section>

<footer class ="row footer">Make sure to follow us on spotify, twitter, and ig</footer>
</main>

</body>
</html>